name: Flutter CI/CD

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Flutter App
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'  

    - name: Install dependencies
      run: flutter pub get

    - name: Run Flutter tests
      run: flutter test

    - name: Build APK (for Android)
      run: flutter build apk --release

    - name: Build iOS (optional, requires macOS runner)
      if: runner.os == 'macOS'
      run: |
        flutter build ios --release
