name: Flutter CI/CD

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Flutter App
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'  

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK (for Android)
      run: flutter build apk --release

    - name: Build iOS (optional, requires macOS runner)
      if: runner.os == 'macOS'
      run: |
        flutter build ios --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Send email with SendGrid API
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: |
        curl -X POST "https://api.sendgrid.com/v3/mail/send" \
          -H "Authorization: Bearer $SENDGRID_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "personalizations": [
              {
                "to": [{"email": "leomarselio@gamatecha.com"}],
                "subject": "Flutter Build APK"
              }
            ],
            "from": {
              "email": "leomarselio@gamatecha.com"
            },
            "content": [
              {
                "type": "text/plain",
                "value": "Hello, this is your Flutter APK build file attached."
              }
            ],
            "attachments": [
              {
                "content": "'"$(base64 -w 0 build/app/outputs/flutter-apk/app-release.apk)"'",
                "filename": "test.apk",
                "type": "application/octet-stream",
                "disposition": "attachment"
              }
            ]
          }'
